# SPDX-License-Identifier: Apache-2.0
#
# Copyright 2024 Ledger SAS

[package]
name = "outpost_kconfig_test_package"
version = "0.1.0"
edition = "2021"

[dependencies]
kconfig = { path = "../../rust/kconfig" }

[build-dependencies]
kconfig_import = { path = "../../rust/kconfig_import" }
