# SPDX-FileCopyrightText: 2024 Ledger SAS
#
# SPDX-License-Identifier: Apache-2.0

version = 1

[[annotations]]
path = ["templates/rustargs.in"]
SPDX-FileCopyrightText = "2024 Ledger SAS"
SPDX-License-Identifier = "Apache-2.0"
